### ISSUE TITLE
Add option to reverse conversation view

### ISSUE THREAD

**Issue by joshsharp** [bellebethcooper/pico#23]
Personally I find the upside-down conversation list of micro dot blog really confusing. I'd like to be able to read it from top to bottom, chronologically, so I'd love an option for this behaviour please!

**Comment by bellebethcooper** [comment]
I've made this the default for now, because it makes more sense to me and matches the Mac app's behaviour. Later on we could add an option for the user to change this behaviour if enough people want it.
