### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by cdn** [bellebethcooper/pico#8]
Assuming I don’t know what I’m doing, how would I approach setting up development on macOS Sierra on a Late 2011 Macbook Pro?

**Comment by bellebethcooper** [comment]
Good point! I don't know that I'll be able to test on this specific environment, but I should definitely add some instructions for building the app. Thanks.

**Comment by cdn** [comment]
![screenshot_1535539825](https://user-images.githubusercontent.com/118273/44783680-0b182f80-ab83-11e8-9bb5-c1290e3fc73b.png)

Get Android Studio
Git clone
Get messages about API 27 being missing
Gradle builds and Emulator runs …
